services:
  signal-service:
    image: docker.io/ahmedatoasis/wt3-signal@sha256:70986bf99f8ecc41f04b9e6f31e4ceceb38aaae36b6e45ae2bc46a8b0934d633
    platform: linux/amd64
    volumes:
      - /run/rofl-appd.sock:/run/rofl-appd.sock
      - /storage/data:/storage/data
    environment:
      - AGE_PRIVATE_KEY=${AGE_PRIVATE_KEY}
      - MOONWARD_API_KEY=${MOONWARD_API_KEY}
    restart: always

  wt3:
    image: docker.io/ahmedatoasis/wt3@sha256:afd8dc9ebaaa816226f862074506fca97f3670717fe1cff480e58df98241a0d2
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - /run/rofl-appd.sock:/run/rofl-appd.sock
      - /storage/data:/storage/data
    environment:
      - GROK_API_KEY=${GROK_API_KEY}
      - TWITTER_BEARER_TOKEN=${TWITTER_BEARER_TOKEN}
      - TWITTER_API_KEY=${TWITTER_API_KEY}
      - TWITTER_API_SECRET=${TWITTER_API_SECRET}
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
      - TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET}
      - SIGNAL_SERVICE_URL=${SIGNAL_SERVICE_URL}
    depends_on:
      - signal-service
    restart: always
