FROM python@sha256:82c07f2f6e35255b92eb16f38dbd22679d5e8fb523064138d7c6468e7bf0c15b

WORKDIR /app

RUN pip install --upgrade pip==25.0.1

COPY requirements.txt .
COPY requirements.signal.txt .
RUN pip install --no-cache-dir -r requirements.signal.txt

RUN apt-get update && \
    apt-get install -y curl=7.88.1-10+deb12u12 && \
    curl -L https://github.com/FiloSottile/age/releases/download/v1.2.1/age-v1.2.1-linux-amd64.tar.gz -o age.tar.gz && \
    tar xzf age.tar.gz && \
    mv age/age /usr/local/bin/ && \
    mv age/age-keygen /usr/local/bin/ && \
    rm -rf age age.tar.gz && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY . .

COPY src/signal_service.tar.gz.age /app/
COPY scripts/signal_entrypoint.sh /app/
RUN chmod +x /app/signal_entrypoint.sh

ENV PYTHONPATH="/app"

CMD ["/app/signal_entrypoint.sh"]